
import sys as _sys, os as _os
_sys.path.insert(0, _os.path.join(_os.path.dirname(_os.path.abspath(__file__)), 'configs'))
from paths import MSR_ROOT, DATA_ROOT, OUTPUT_ROOT, WEIGHTS, PREDICTIONS

import os
from pathlib import Path


def create_geographic_split(train_dir, val_dir, test_dir, output_dir):
    """
    Create train.txt, val.txt, test.txt for SatMAE segmentation.

    Each region is a separate directory of chips generated by
    satmae_chip_generation.py. The split is geographic -- different
    spatial regions assigned to train / val / test, consistent with
    the benchmark design in the report.

    Args:
        train_dir:  directory containing training region chips
        val_dir:    directory containing validation region chips
        test_dir:   directory containing test region chips
        output_dir: directory where train.txt/val.txt/test.txt are saved
                    (should be the same dir your SLURM script points to)
    """
    train_dir  = Path(train_dir)
    val_dir    = Path(val_dir)
    test_dir   = Path(test_dir)
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    print("=" * 70)
    print("SATMAE GEOGRAPHIC TRAIN/VAL/TEST SPLIT")
    print("=" * 70)

    def get_chip_names(directory):
        """Get sorted list of chip stems, excluding mask files."""
        all_tifs = sorted(directory.glob("chip_*.tif"))
        chips = [f.stem for f in all_tifs if "_mask" not in f.name]
        return chips

    # ----------------------------------------------------------------
    # Train
    # ----------------------------------------------------------------
    print(f"\nProcessing TRAIN region: {train_dir.name}")
    train_chips = get_chip_names(train_dir)
    print(f"  Found {len(train_chips)} chips")
    if train_chips:
        print(f"  Example: {train_chips[0]}")

    train_txt = output_dir / "train.txt"
    with open(train_txt, "w") as f:
        for name in train_chips:
            f.write(f"{name}\n")
    print(f"  Saved: {train_txt}")

    # ----------------------------------------------------------------
    # Val
    # ----------------------------------------------------------------
    print(f"\nProcessing VAL region: {val_dir.name}")
    val_chips = get_chip_names(val_dir)
    print(f"  Found {len(val_chips)} chips")
    if val_chips:
        print(f"  Example: {val_chips[0]}")

    val_txt = output_dir / "val.txt"
    with open(val_txt, "w") as f:
        for name in val_chips:
            f.write(f"{name}\n")
    print(f"  Saved: {val_txt}")

    # ----------------------------------------------------------------
    # Test
    # ----------------------------------------------------------------
    print(f"\nProcessing TEST region: {test_dir.name}")
    test_chips = get_chip_names(test_dir)
    print(f"  Found {len(test_chips)} chips")
    if test_chips:
        print(f"  Example: {test_chips[0]}")

    test_txt = output_dir / "test.txt"
    with open(test_txt, "w") as f:
        for name in test_chips:
            f.write(f"{name}\n")
    print(f"  Saved: {test_txt}")

    # ----------------------------------------------------------------
    # Summary
    # ----------------------------------------------------------------
    print("\n" + "=" * 70)
    print("SUMMARY")
    print("=" * 70)
    print(f"Train: {len(train_chips):>5} chips  <- {train_dir.name}")
    print(f"Val:   {len(val_chips):>5} chips  <- {val_dir.name}")
    print(f"Test:  {len(test_chips):>5} chips  <- {test_dir.name}")
    print(f"\nOutput directory: {output_dir}")
    print(f"  {train_txt.name}")
    print(f"  {val_txt.name}")
    print(f"  {test_txt.name}")
    print("=" * 70)

    return train_chips, val_chips, test_chips


if __name__ == "__main__":

    # ================================================================
    # UPDATE THESE PATHS
    # Iowa example: Ames=train, CedarRapids=val, Sheldon=test
    # (same geographic split logic as Prithvi and SpectralGPT)
    # ================================================================

    TRAIN_DIR  = f"{DATA_ROOT}/SatMAE_chips_multitemporal/CentIA"
    VAL_DIR    = f"{DATA_ROOT}/SatMAE_chips_multitemporal/EastIA"
    TEST_DIR   = f"{DATA_ROOT}/SatMAE_chips_multitemporal/NWIA"

    # Output -- chips from all three regions should be accessible from here.
    # Since dataset_seg.py reads chip files from data_path, all chips
    # (train + val + test) must be in the SAME directory OR you update
    # data_path per split. Simplest approach: put all chips in one dir
    # and use split txts to select which ones to use.
    #
    # Option A (recommended): all chips in one merged directory
    OUTPUT_DIR = f"{DATA_ROOT}/SatMAE_chips_multitemporal/Iowa"

    # Option B: split txts live in the train dir, val/test chips elsewhere
    # -- requires updating dataset_seg.py to handle multiple data dirs
    # Not recommended for simplicity.

    print("=" * 70)
    print("SATMAE GEOGRAPHIC TRAIN/VAL/TEST SPLIT GENERATION")
    print("=" * 70)
    print(f"Train dir:  {TRAIN_DIR}")
    print(f"Val dir:    {VAL_DIR}")
    print(f"Test dir:   {TEST_DIR}")
    print(f"Output dir: {OUTPUT_DIR}")
    print()

    train_chips, val_chips, test_chips = create_geographic_split(
        TRAIN_DIR, VAL_DIR, TEST_DIR, OUTPUT_DIR
    )

    print("\nDone! Next steps:")
    print("  1. Update SLURM script CHIPS_DIR to point to OUTPUT_DIR")
    print("  2. Run: sbatch train_satmae_seg.sh")